---
title: "응용프로그래밍 R 최종"
author: "금융정보통계학과 이기원교수"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=180)
rm(list=ls())
```

```{r, presets, , message = FALSE, echo = FALSE}
options(digits=3)
library(readxl)
library(knitr)
library(magrittr)
library(pander)
panderOptions("table.split.table", Inf)
```


<!--### Total Scores-->

## 점수 분포표

신현재에게 우수 Q&A 인센티브 1점을 총점에 추가

```{r, Total Scores, message = FALSE, echo = FALSE}
total <-
  read_excel(path = "./data/AR_score_2302_v2.xlsx",
             range = "A1:G50")
total %<>%
  `names<-`(c("Name", "ID", "Assignment", "Quiz", "Team_Project", "Online", "Total"))
## 신현재에게 우수 Q&A 인센티브 1점 부여
# total[total$Name == "신현재", "Total"] <- total[total$Name == "신현재", "Total"] + 1
N <- nrow(total)
total$Total %>%
  stem
total$Total %>% 
  cut(breaks = c(0, 60, 85, 90, 100),
      labels = c("D+/F : [0 ~ 40)", 
                 "C+ : [40 ~ 85)", 
                 "B+ : [85 ~ 90)", 
  #               "A0 : [90 ~ 95)", 
                 "A+ : [90 ~ 100]"), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  rev %>% 
  t %>% 
  `row.names<-`("Counts") %>%
# row.names(scores_tbl) <- "Counts"
# scores_tbl %>%
  cbind("계" = rowSums(.)) %>%
  t %>%
  pander()
total$Ranks <- N + 1 - rank(total$Total)
# total$Grades <- ifelse(total$Ranks <= floor(N*0.5), "A+", ifelse(total$Ranks <= floor(N*0.7), "B+", "C+"))
total$Grades <- total$Total %>% 
  cut(breaks = c(0, 40, 85, 90, 100), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  factor(levels = c("[90,100]", 
                    "[85,90)", 
                    "[40,85)", 
                    "[0,40)"),
         labels = c("A+", "B+", "C+", "D+"))
levels(total$Grades) <- c(levels(total$Grades), "F")
total$Grades[total$Total == 0] <- "F"
counts <- 
  total$Grades %>%
  table %>% 
  c("계" = sum(.))
perc <- 
  total$Grades %>%
  table %>% 
  prop.table %>%
  c("계" = sum(.)) %>%
  `*`(100) %>%
  round(digits = 2)
# o.names <- order(total$Name)
v.names.kr <- c("이름", "학번", "과제(30)", "퀴즈(20)", "팀 프로젝트(30)", "온라인출석(20)","총점(100)", "순위(49명중)", "학점")
total.kr <- total
names(total.kr) <- v.names.kr
total %>%
  `names<-`(c("이름", "학번", "과제(30)", "퀴즈(20)", "팀 프로젝트(30)", "온라인출석(20)", "총점(100)", "순위(49명중)", "학점")) %>%
  `[`(total$Name %>% order, ) %>%
  kable(row.names = FALSE)
# kable(total.kr[o.names, ], row.names = FALSE)
# kable(total)
```


<P style = "page-break-before:always">

```{r, individual scores, echo = FALSE}
my.grade <- function(name){
  kable(total.kr[total$Name %in% name, -1], row.names = FALSE)
}
# my.grade("신현재")
# my.grade(c("김필준", "최민영", "정원동", "김지우", "홍유진", "김동준", "최민기"))
```


<!--### Save Data

```{r Save Data, echo = FALSE}
save.image(file = "../R/AR_records_02.RData")
```

-->
               