---
title: "Class Roll"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
library(dplyr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data, echo = TRUE, results = 'show', warning = TRUE}
getwd()
class_roll0304 <- read_excel("./data/class_roll_250304.xlsx", 
                        range = "B1:H612")
str(class_roll0304)
names(class_roll0304) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0304)
class_roll0306 <- read_excel("./data/class_roll_250306.xlsx", 
                        range = "B1:H611")
str(class_roll0306)
names(class_roll0306) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0306)
class_roll0307 <- read_excel("./data/class_roll_250307.xlsx", 
                        range = "B1:H611")
str(class_roll0307)
names(class_roll0307) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0307)
class_roll0308 <- read_excel("./data/class_roll_250308.xlsx", 
                        range = "B1:H611")
str(class_roll0308)
names(class_roll0308) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0308)
class_roll0309 <- read_excel("./data/class_roll_250309.xlsx", 
                        range = "B1:H611")
str(class_roll0309)
names(class_roll0309) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0309)
class_roll0310 <- read_excel("./data/class_roll_250310.xlsx", 
                        range = "B1:H611")
str(class_roll0310)
names(class_roll0310) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0310)
class_roll0314 <- read_excel("./data/class_roll_250314.xlsx", 
                        range = "B1:H611")
str(class_roll0314)
names(class_roll0314) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0314)
class_roll0317 <- read_excel("./data/class_roll_250317.xlsx", 
                        range = "B1:H610")
str(class_roll0317)
names(class_roll0317) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0317)
class_roll0321 <- read_excel("./data/class_roll_250321.xlsx", 
                        range = "B1:H605")
str(class_roll0321)
names(class_roll0321) <- c("dept", "college", "id", "name", "status", "email", "cell_no")
str(class_roll0321)
setdiff(class_roll0304$id, class_roll0306$id)
setdiff(class_roll0306$id, class_roll0304$id)
setdiff(class_roll0306$id, class_roll0307$id)
setdiff(class_roll0307$id, class_roll0306$id)
setdiff(class_roll0308$id, class_roll0307$id)
setdiff(class_roll0307$id, class_roll0308$id)
setdiff(class_roll0308$id, class_roll0309$id)
setdiff(class_roll0309$id, class_roll0308$id)
id_out_23 <- setdiff(class_roll0308$id, class_roll0310$id)
id_new_23 <- setdiff(class_roll0310$id, class_roll0308$id)
id_out_4 <- setdiff(class_roll0310$id, class_roll0314$id)
id_new_4 <- setdiff(class_roll0314$id, class_roll0310$id)
id_out_5 <- setdiff(class_roll0314$id, class_roll0317$id)
id_new_5 <- setdiff(class_roll0317$id, class_roll0314$id)
id_out_6 <- setdiff(class_roll0317$id, class_roll0321$id)
id_new_6 <- setdiff(class_roll0321$id, class_roll0317$id)
# data.frame(class_roll0310$id, class_roll0308$id)
```
