---
title: "데이터실험 댓글 점수 확인"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr")
library(readxl)
library(readr)
library(pander)
library(knitr)
library(dplyr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 132)
```

# Data

# 댓글 제출시간 데이터

```{r, data, echo = FALSE, message = FALSE, results = "hide"}
options(digits = 2)
class_roll <- readRDS("./class_roll_240913.RDS")
class_roll <- data.frame(class_roll)
comment <-
  read_excel("./data/data_lab_241118.xlsx",
             range = "A2:H8375", 
             col_names = TRUE)
str(comment)
#> csv 인 경우
# comment <-
#   read_csv("./data/data_lab_220503.csv")
comment <- comment[, -c(2, 3)]
names(comment) <- c("title", "time1", "contents", "name", "id", "time2")
str(comment)
class(comment$id) <- "character"
## 잘못 올라오거나 주석처리한 덧글을 정리하기 위하여 반드시 검토하여야 함.
table(comment$title)
#> 집계 기간 중에 올라 온 오류 수정
which(comment$title == "03. Quiz 240301 집계결과 분석 (부연설명의 효과, 집계 중이므로 열람 O, 댓글 X)")
comment[comment$title == "03. Quiz 240301 집계결과 분석 (부연설명의 효과, 집계 중이므로 열람 O, 댓글 X)", "title"] <-
  "03. Quiz 240301 집계결과 분석 (부연설명의 효과)"
comment[comment$title == "04. Quiz 240909 집계\035중 (Cheating Charts, 열람 O, 댓글 X)", "title"] <-
  "04. Quiz 240909 집계\035결과 요약 (Cheating Charts)"
comment[comment$title == "05. Quiz 240315 집계결과 집계중 (Bias in Question, 열람 O, 댓글 X)", "title"] <-
  "05. Quiz 240916 집계결과 요약 (Bias in Question)"
comment[comment$title == "05. Quiz 240315 집계결과 요약 (Bias in Question)", "title"] <-
  "05. Quiz 240315 집계결과 요약 (Bias in Question)"
#> 수정된 결과 확인
table(comment$title)
N_labs <- 15
N_students <- nrow(class_roll)
comment$title_f <- comment$title %>%
  factor(labels = 1:N_labs)
#> 청강생 처리
# not_student <- comment$id %in% c("44079", "44450", "89022", "aidma1", "yoonmee")
# !not_student
# comment <- comment[!not_student, ]
str(comment)
```

## 게시 후 2주 이내 1점, 지나면 0.7점 부여 (11월 18일 12:00 기준)

```{r, echo = FALSE, message = FALSE}
## 미제출자 NA 처리하기 위하여 출석부와 `left_join`. title이 너무 길어서 회차만 뗴어 factor로 재구조화
#> 1회차 예시. 옛 규칙.
comment01 <- left_join(class_roll[, c("id", "name")], 
                       comment[comment$title_f == 1, -c(1, 3)], 
                       by = c("id", "name"))
## 게시후 제출까지의 기간을 주 단위로 연산
comment01$weeks <- as.numeric(difftime(comment01$time2, comment01$time1, 
                                       units = 'weeks')) 
## 옛 규칙 : 6주가 지나거나 미제출은 0점 처리, 1주일 지날 때 마다 0.2점씩 감점. 계산식에 유의.
comment01$score <- ifelse(comment01$weeks > 6 
                          | is.na(comment01$weeks), 0,  
                          pmin(1, floor(7 - comment01$weeks) / 5)) 
#                           ifelse(comment01$weeks > 5, 0.2,
#                                  ifelse(comment01$weeks > 4, 0.4,
#                                         ifelse(comment01$weeks > 3, 0.6,  
#                                                ifelse(comment01$weeks > 2, 0.8, 1)))))
## 변수 순서 정리
comment01 <- comment01[c("id", "name", "title_f", "time1", "time2", "weeks", "score")]
## 회차 결측값 채우기
comment01$title_f[is.na(comment01$title_f)] <- 1
## 중복 제출 자료는 2차에 제출한 자료를 삭제
comment01 <- comment01[!duplicated(comment01$id), ]
comment01

## 회차별로 점수를 포함한 데이터 생성하는 함수 작성

df <- function(j){  
  comments <- left_join(class_roll[, c("id", "name")], 
                        comment[comment$title_f == j, -c(1, 3)], 
                        by = c("id", "name"))
  comments$weeks <- as.numeric(difftime(comments$time2, comments$time1, 
                                        units = 'weeks'))
  comments$score <- ifelse(is.na(comments$weeks), 0,
                           ifelse(comments$weeks > 2.0, 0.7, 1))
#  comments$score <- ifelse(comments$weeks > 6
#                           | is.na(comments$weeks), 0, 
#                           pmin(1, floor(7 - comments$weeks) / 5))
#                           ifelse(comments$weeks > 5, 0.2,
#                                  ifelse(comments$weeks > 4, 0.4,
#                                         ifelse(comments$weeks > 3, 0.6,  
#                                                ifelse(comments$weeks > 2, 0.8, 1)))))
  comments <- comments[c("id", "name", "title_f", "time1", "time2", "weeks", "score")]
  comments$title_f[is.na(comments$title_f)] <- j
  comments <- comments[!duplicated(comments$id), ]
  return(comments)
}
```

# 회차별 점수 계산

```{r, echo = FALSE, eval = TRUE, results = 'hide'}
library(dplyr)

# 각 회차별로 df(j) 함수를 적용하여 list 생성 후, bind_rows()로 결합
comments <- lapply(1:N_labs, df) %>%
  bind_rows()
```

```{r, echo = FALSE, eval = FALSE, results = 'hide'}
## 초기화
comments <- NULL 

## `rbind`를 이용하여 회차별로 생성한 데이터를 long form data frame 으로 구조화
for (j in 1:N_labs) {
  comments <- rbind(comments, df(j))
}

# kable(comments[, -2], row.names = FALSE)
```

# 점수 합산


```{r, echo = FALSE, eval = FALSE}
## 학번별로 회차별 점수 합산
total <- comments %>%
  group_by(id) %>%
  summarize(total_score = sum(score, na.rm = TRUE))
```

```{r, echo = FALSE, eval = TRUE}
## 학번별로 회차별 점수 합산
total <- comments %$%
  tapply(score, id, sum)
```

# 점수 집계 요약 (id 순)

```{r, echo = FALSE, eval = FALSE}
library(tidyr)

# 필요한 변수 선택 후 wide 형식으로 변환
comments_w <- comments %>%
  select(id, name, title_f, time1, time2, weeks, score) %>%
  pivot_wider(
    id_cols = c(id, name),                   # 'id'와 'name'을 기준 열로 설정
    names_from = title_f,                     # 회차별 구분 열
    values_from = c(time1, time2, weeks, score), 
    names_sep = "_",                          # 각 회차를 구분하기 위해 구분자 설정
    names_prefix = "s"                        # 변수명 앞에 "s" 추가
  )
```

```{r, echo = FALSE, eval = TRUE}
options(digits = 4)
## Wide form으로 전환하기 위하여 초기 데이터 프레임 설정
comments_w <- comments[1:N_students, c("id", "name")]

## Wide form으로 재구조화하고 변수 이름을 회차별로 구분하도록 설정
for (j in 1:N_labs) {
  comments_w <- cbind(comments_w, comments[comments$title_f == j, c("time1", "time2", "weeks", "score")])
  names(comments_w)[(4 * j + 1):(4 * j + 2)] <- 
    paste(substr(names(comments_w)[(4 * j + 1):(4 * j + 2)], 1, 1), j, sep = "_")
  names(comments_w)[(4 * j - 1):(4 * j)] <- 
    paste(names(comments_w)[(4 * j - 1):(4 * j)], j, sep = "_")
}

comments_w$total <- total[match(comments_w$id, names(total))]

# comments_w$total <- comments_w$total * 5

kable(comments_w[order(comments_w$id, comments_w$name), 
                 c("id", paste("s", 1:N_labs, sep = "_"), "total")], 
      digits = 4,
      row.names = FALSE)

# pander(comments_w[order(comments_w$id, comments_w$name), 
#                  c("id", "total")], 
#       row.names = FALSE)
```

# 회차별 점수 

```{r, echo = FALSE}
kable(comments[order(comments$id), -2], row.names = FALSE)
```

# Red and Black

## 기초통계값 비교

최소값, 제1사분위수, 중위수, 산술평균, 제3사분위수, 최대값. 닮았나요?  

```{r}
comments_w$group <- class_roll$group[match(comments_w$id, class_roll$id)]
tapply(comments_w$total, comments_w$group, summary) %>% 
  pander
```

## 표준편차

```{r}
tapply(comments_w$total, comments_w$group, sd) %>%
  pander
```

## 댓글을 아직 한번도 올리지 않은 사람의 수효

```{r}
tapply(comments_w$total == 0, comments_w$group, sum) %>%
  pander
```

## t-test

p-value 를 보고 판단하세요.

```{r, fig.width = 7, fig.height = 7}
t.test(comments_w$total ~ comments_w$group) %>%
  pander
```

## QQplot 

기울기가 45도에 가까운가요?

```{r, fig.width = 7, fig.height = 7}
qqplot(comments_w$total[comments_w$group == "Red"], 
       comments_w$total[comments_w$group == "Black"],
       main = "QQplot for Red and Black",
       xlab = "Red", 
       ylab = "Black")
```

<!--
Save
-->

```{r, echo = FALSE}
write.csv(comments, file = "./data/comments241118.csv", 
          row.names = FALSE,
          fileEncoding = "CP949")
write.csv(comments_w[order(comments_w$name, comments_w$id), 
                 c("id", "name", paste("s", 1:N_labs, sep = "_"), "total")],
          file = "./data/comments241118_w.csv", 
          row.names = FALSE,
          fileEncoding = "CP949")
saveRDS(comments_w[order(comments_w$name, comments_w$id), 
                 c("id", "name", "group", "total")],
        file = "./data_lab241118.RDS")
save.image(file = "./data_lab241118.RData")
```
