---
title: "데이터실험 댓글 점수 확인"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(dplyr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 132)
```

```{r, data, echo = FALSE, message = FALSE, results = "hide"}
options(digits = 2)
load("./data_lab221130.RData")
str(comments)
str(comments_w)
```

# Red and Black

## 기초통계값 비교

최소값, 제1사분위수, 중위수, 산술평균, 제3사분위수, 최대값. 닮았나요?  

```{r}
comments_w$group <- class_roll0909$group[match(comments_w$id, class_roll0909$id)]
tapply(comments_w$total, comments_w$group, summary) %>% 
  pander
```

## 표준편차

```{r}
tapply(comments_w$total, comments_w$group, sd) %>%
  pander
```

## 댓글을 아직 한번도 올리지 않은 사람의 수효

```{r}
tapply(comments_w$total == 0, comments_w$group, sum) %>%
  pander
```

## t-test

p-value 를 보고 판단하세요.

```{r, fig.width = 7, fig.height = 7}
t.test(comments_w$total ~ comments_w$group) %>%
  pander
```

## QQplot 

기울기가 45도에 가까운가요?

```{r, fig.width = 7, fig.height = 7}
qqplot(comments_w$total[comments_w$group == "Red"], 
       comments_w$total[comments_w$group == "Black"],
       main = "QQplot for Red and Black",
       xlab = "Red", 
       ylab = "Black")
```

<!--
# 한번도 댓글을 올리지 않은 사람들

```{r, echo = FALSE, results = "asis"}
comments_w[comments_w$total == 0, c("id", "name")] %>%
  pander
```
-->

# 점수 집계 요약 (id 순)

```{r, echo = FALSE}
options(digits = 4)
kable(comments_w[order(comments_w$id, comments_w$name), 
                 c("id", paste("s", 1:N_labs, sep = "_"), "total")], 
      digits = 4,
      row.names = FALSE)
```

# 회차별 점수 

```{r, echo = FALSE}
kable(comments[order(comments$id), -2], row.names = FALSE)
```
