---
title: "생활 속의 통계학 최종"
author: "데이터사이언스학부 이기원교수"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=180)
```

```{r, presets, , message = FALSE, echo = FALSE}
options(digits = 3)
library(readxl)
library(knitr)
library(pander)
library(magrittr)
panderOptions("table.split.table", Inf)
```

```{r, Total Scores, message = FALSE, echo = FALSE}
# total <- read.xlsx(file = "../data/final_score_2102.xlsx", 
#                    sheetIndex = 1, 
#                    rowIndex = 1:305, 
#                    colIndex = c(1, 3, 7:12), 
#                    colClasses = c(rep("character", 2), rep("numeric", 6)), 
#                    header = TRUE,
#                    stringsAsFactors = FALSE)
## read_excel 에서 숫자를 자꾸 time 객체로 인식하는 문제 등이 발생하여 모두 text 로 읽어들이고 unclass 한 후 숫자로 class 
class_roll_final <- 
  read_excel(path = "../data/class_roll_final2202.xlsx",
             range = "A1:B1042",
             col_types = rep("text", 2))
class_roll_final %<>%
  data.frame
names(class_roll_final) <- c("ID", "Name")
total <-
  read_excel(path = "../data/Final_Records_2202.xlsx",
             range = "A1:L1058",
             col_types = c(rep("text", 6), rep("numeric", 6)))

total <- data.frame(total)
total[, 7:12] <- sapply(total[, 7:12], unclass)
nas <- which(is.na(total), arr.ind = TRUE)
total[nas] <- 0.0
total[, 7:12] <- sapply(total[, 7:12], function(x)`class<-`(x, "numeric"))
# str(total)
total <- total[c(3, 1, 7:12)]
# total <- total[c(2, 1, 3:8)]
v_names_total <- c("ID", "Name", "Quiz", "TED", "Online_Att", "Data_Lab", "Google_Att", "Total")
names(total) <- v_names_total
# class(total[, "Google_Att"]) <- "numeric"
## 점수 환산
# total[, "Google_Att"] <- total[, "Google_Att"] * 0.05
# total[, "Data_Lab"] <- total[, "Data_Lab"] * 0.3
army_ID <- setdiff(total$ID, class_roll_final$ID)
army_records <- total[total$ID %in% army_ID, ] 
total <- total[total$ID %in% setdiff(total$ID, army_ID), ]
```
## 군휴학생 성적부

```{r}
pander(army_records, row.names = FALSE)
```

<!--
## FA 명단
 
```{r, FA_list, eval = TRUE, message = FALSE, echo = FALSE}
FA_id <- c("20171701", "20155219")
FA <- total$ID %in% FA_id
total[FA, "Name"]
```

## 대체/재이수 명단

```{r, eval = TRUE, message = FALSE, echo = FALSE}
(Repl_names <- c("김범수", "김세원", "김용규", "김은지", "김정민", "김준모", "노흥승", "맹소진", "박준영", "심무중", "윤성민", "이명규", "이연희", "이예진", "이학무", "정영광", "주소원", "한예지", "홍예은", "황푸름"))
Repl <- total$Name %in% Repl_names
```
-->

## 재학생 점수 히스토그램

```{r, message = FALSE, echo = FALSE}
# if(sum(FA) > 0) {
#     total <- total[!FA, ]
#  }

#> 점수분포표
total$Total %>%  
  cut(breaks = seq(0, 100, by = 10), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  as.matrix %>%
  t %>%
  pander
h <- 
  total$Total %>% 
  hist(breaks = seq(0, 100, by = 5), 
       include.lowest = TRUE,
       right = FALSE,
       yaxt = "n",
       prob = FALSE, 
       col = "white",
       main = "Histogram")
axis(side = 1, at = seq(0, 100,  by = 10), labels = seq(0, 100, by = 10))
axis(side = 2, at = h$counts, labels = h$counts, las = 2)
```

## 재학생 점수 분포표

```{r, echo = FALSE}
Counts_tbl <- total$Total %>% 
  cut(breaks = c(0, 20, 40, 50, 60, 80, 90, 95, 98, 100),
      labels = c("[0 ~ 20)", 
                 "[20 ~ 40)",
                 "[40 ~ 50)",
                 "[50 ~ 60)", 
                 "[60 ~ 80)", 
                 "[80 ~ 90)", 
                 "[90 ~ 95)",
                 "[95 ~ 98)", 
                 "[98 ~ 100]"), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  rev %>% 
  t %>% 
  `row.names<-`("Counts") %>%
# row.names(scores_tbl) <- "Counts"
# scores_tbl %>%
  cbind("계" = rowSums(.)) %>%
  t
Prop_tbl <- total$Total %>% 
  cut(breaks = c(0, 20, 40, 50, 60, 80, 90, 95, 98, 100),
      labels = c("[0 ~ 20)", 
                 "[20 ~ 40)",
                 "[40 ~ 50)",
                 "[50 ~ 60)", 
                 "[60 ~ 80)", 
                 "[80 ~ 90)", 
                 "[90 ~ 95)",
                 "[95 ~ 98)", 
                 "[98 ~ 100]"), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  prop.table %>%
  `*`(100) %>%
  round(digits = 2) %>%
  rev %>% 
  t %>% 
  `row.names<-`("Percentages") %>%
# row.names(scores_tbl) <- "Counts"
# scores_tbl %>%
  cbind("계" = rowSums(.)) %>%
  t 
Grades <- c("A+", "A0", "B+", "B0", "C+", "C0", "D+", "D0", "F", "")
cbind(Counts_tbl, Prop_tbl, Grades) %>%
  pander()
```

## 성적 등급 

```{r, message = FALSE, echo = FALSE}
# str(total)
total$Grades <- total$Total %>% 
  cut(breaks = c(0, 50, 100), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  factor(levels = c("[50,100]", 
                    "[0,50)"),
         labels = c("Pass", "Non-Pass"))
counts <- total$Grades %>%
  table %>% 
  c("계" = sum(.))
perc <- total$Grades %>%
  table %>% 
  prop.table %>%
  c("계" = sum(.)) %>%
  `*`(100) %>%
  round(digits = 2) 
#> 대체 수강자 중 A+ => A0
counts2 <- total$Grades %>%
  table %>% 
  c("계" = sum(.))
perc2 <- total$Grades %>%
  table %>%
  prop.table %>%
  c("계" = sum(.)) %>%
  `*`(100) %>%
  round(digits = 2) 
# rbind("Counts" = counts2, 
#       "Percentage" = perc2, 
#       "Cumulative" = cumsum(perc2)) %>%
#   cbind("Sum" = rowSums(.)) %>%
#  format(digits = 1, nsmall = 1) %>%
rbind("Counts" = format(counts2, digits = 1, nsmall = 0), 
      "Percentage(%)" = format(perc2, digits = 1, nsmall = 1), 
      "Cumulative(%)" = format(cumsum(perc2), digits = 1, nsmall = 1)) %>%
# cbind("Sum" = rowSums(.)) %>%
#   format(digits = 1, nsmall = 1) %>%
  `[<-`(3, 3, "") %>%
  kable(align = "r")
```

## 성적 산출 내역

```{r, message = FALSE, echo = FALSE}
# str(total)
total %>% 
  `[`(order(total$Name, total$ID), ) %>%
  kable(align = c(rep("c", 2), rep("r", 6), "c"), row.names = FALSE)
```

<!--
## 재수강을 고려한 특별 강등 요청

```{r, message = FALSE, echo = FALSE}
total[total$Name == "김수빈", ] %>%
  kable(align = c(rep("c", 2), rep("r", 6), "c"))
```

## Quiz 19점 이상

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Quiz >= 19, ], digits = 2, nsmall = 1),
      align = c(rep("r", 8), "c"))
nrow(total[total$Quiz >= 19, ])
```

## 60점 미만

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Total < 60, ], digits = 2, nsmall = 1),
      align = c(rep("r", 8), "c"))
nrow(total[total$Total < 60, ])
```
-->

<!--
## 50점 미만

```{r, eval = TRUE, echo = FALSE}
total[total$Total < 50, "Name"]
nrow(total[total$Total < 40, ])
```

##  A 학점자

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Grades %in% c("A+", "A0"), ], digits = 2, nsmall = 1), 
      align = c(rep("r", 8), "c"), digits = 3)
nrow(total[total$Grades %in% c("A+", "A0"), ])
```
-->


<P style = "page-break-before:always">

```{r, individual scores, eval = TRUE, echo = FALSE}
v_names_kr <- c("학번", "이름","퀴즈(20)", "TED(25)", "온라인출석(20)", "데이터실험(30)", "구글설문지(5)" , "총점(100)", "학점")
total_kr <- total 
names(total_kr) <- v_names_kr
my_grade <- function(name){
  kable(total_kr[total$Name %in% name, -1], row.names = FALSE)
}
my_grade <- function(name){
  kable(total_kr[total$Name %in% name, -1], 
        row.names = FALSE)
}
my_grade(c("이기호"))
my_grade(c("홍예원"))
my_grade(c("최서연"))
my_grade(c("박가누"))
```

```{r, eval = FALSE, echo = FALSE}
my_grade_print <-
  function(name){
    paste(names(total_kr[total$Name %in%  name, -c(1, 9)]),
          total_kr[total$Name %in% name, -c(1, 9)], 
          sep = ":", 
          collapse = "\t")
  }
cat(my_grade_print("이기호")) 
sapply(c("가해린", "박가누"), my_grade_print) %>%
  kable(escape = FALSE, row.names = FALSE)
sapply(total[total$Total < 50, "Name"], 
       FUN = my_grade_print) %>%
  kable(escape = FALSE, row.names = FALSE)
```


<!--
### Save Data

```{r Save Data, echo = FALSE}
write.csv(army_records, file = "../data/army_records_2202.csv", 
          row.names = FALSE,
          fileEncoding = "CP949")
army_records
total2202 <- total
saveRDS(total2202, file = "total2202.RDS")
save.image(file = "../R/final_Records2202.RData")
```

-->
               