---
title: "생활 속의 통계학 최종"
author: "데이터사이언스학부 이기원교수"
date: "2025-12-21"
# date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
# output: html_document
output:
  pdf_document:
    latex_engine: xelatex
    dev: cairo_pdf
    keep_tex: true
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{NanumGothic}
  - \setsansfont{NanumGothic}
  - \setmonofont{NanumGothic}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=180)
library(showtext)
font_add(family = "nanum", 
         regular = "~/Library/Fonts/NanumGothic-Regular.ttf",
         bold    = "~/Library/Fonts/NanumGothic-Bold.ttf",
         italic  = "~/Library/Fonts/NanumGothic-ExtraBold.ttf")
showtext_auto()
```

```{r, presets, , message = FALSE, echo = FALSE}
options(digits = 3)
library(readxl)
library(knitr)
library(pander)
library(magrittr)
library(dplyr)
panderOptions("table.split.table", Inf)
```

```{r, Total Scores, message = FALSE, echo = FALSE, warning = FALSE}
class_roll <- readRDS("./class_roll_251220.RDS")
total <-
  read_excel(path = "./data/Final_Records_2502_1220.xlsx",
             range = "A1:L605",
             col_types = c(rep("text", 6), rep("numeric", 6)))
total <- data.frame(total)
# total[, 7:12] <- sapply(total[, 7:12], unclass)
nas <- which(is.na(total), arr.ind = TRUE)
total[nas] <- 0.0
# total[which(total == "-", arr.ind = TRUE)]
# total[, 7:12] <- sapply(total[, 7:12], function(x)`class<-`(x, "numeric"))
# str(total)
total <- total[c(3, 1, 7:12)]
# total <- total[c(2, 1, 3:8)]
v_names_total <- c("ID", "Name", "Online_Att", "Online_Quiz", "TED_Quiz", "Data_Lab", "Google_Att", "Total")
names(total) <- v_names_total
# class(total[, "Google_Att"]) <- "numeric"
## 점수 환산
# total[, "Google_Att"] <- total[, "Google_Att"] * 0.05
# total[, "Data_Lab"] <- total[, "Data_Lab"] * 0.3
# army_ID <- setdiff(total$ID, class_roll_final$ID)
army_ID <- 
  c("20215164", 
    "20215274", 
    "20231524", 
    "20233008", 
    "20233840", 
    "20235236", 
    "20235241", 
    "20243213",
    "20243353",
    "20243535",
    "20245139",
    "20245247",
    "20246145",
    "20246735",
    "20256186")
army_records <- total[total$ID %in% army_ID, ] 
total <- total[total$ID %in% setdiff(total$ID, army_ID), ]
```
## 군휴학생 성적부

```{r, echo = FALSE}
pander(army_records[order(army_records$ID), ], row.names = FALSE)
```

## FA 명단
 
```{r, FA_list, eval = TRUE, message = FALSE, echo = FALSE}
FA_id <- 
  c("20251001", "20215266", "20251204", "20252326", "20233414",
    "20243819", "20237091", "20215244", "20205245")
FA <- total$ID %in% FA_id
total[FA, c("ID", "Name")] %>%
  arrange(Name) %>%
  pander
```

<!--## 대체/재이수 명단

```{r, eval = TRUE, message = FALSE, echo = FALSE}
(Repl_names <- c("김범수", "김세원", "김용규", "김은지", "김정민", "김준모", "노흥승", "맹소진", "박준영", "심무중", "윤성민", "이명규", "이연희", "이예진", "이학무", "정영광", "주소원", "한예지", "홍예은", "황푸름"))
Repl <- total$Name %in% Repl_names
```
-->

\newpage

## 재학생 점수 히스토그램

```{r, message = FALSE, echo = FALSE}
par(family = "nanum")
if(sum(FA) > 0) {
    total <- total[!FA, ]
    }

#> 점수분포표
total$Total %>%  
  cut(breaks = seq(0, 100, by = 10), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  as.matrix %>%
  t %>%
  pander
h <- 
  total$Total %>% 
  hist(breaks = seq(0, 100, by = 5), 
       include.lowest = TRUE,
       right = FALSE,
       yaxt = "n",
       prob = FALSE, 
       col = "white",
       main = "총점 히스토그램")
axis(side = 1, at = seq(0, 100,  by = 10), labels = seq(0, 100, by = 10))
axis(side = 2, at = h$counts, labels = h$counts, las = 2)
```

```{r, message = FALSE, echo = FALSE, eval = FALSE}
library(ggplot2)
if(sum(FA) > 0) {
    total <- total[!FA, ]
    }

#> 점수분포표
total$Total %>%  
  cut(breaks = seq(0, 100, by = 10), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  as.matrix %>%
  t %>%
  pander

ggplot(total, aes(x = Total)) +
  geom_histogram(
    breaks = seq(0, 100, by = 5), 
    color = "black", fill = "white", 
    boundary = 0, closed = "left", na.rm = TRUE) +
  scale_x_continuous(
    breaks = seq(0, 100, by = 10), 
    limits = c(0, 100)) +
  scale_y_continuous(
    breaks = h$counts,  # y축 눈금을 실제 count 값에 맞춤
    labels = h$count,
    expand = expansion(mult = c(0, 0.05))  # y축 여백 약간
  ) +
  labs(
    title = "총점 히스토그램", x = "총점", y = "빈도수"
  ) +
  theme_minimal(base_family = "nanum") + # showtext 폰트 설정 시 유용
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5))  
```
\newpage

## 재학생 점수 분포표

```{r, echo = FALSE}
Counts_tbl <- total$Total %>% 
  cut(breaks = c(0, 20, 40, 60, 90, 96, 100),
      labels = c("[0 ~ 20)", 
                 "[20 ~ 40)",
                 "[40 ~ 60)",
                 "[60 ~ 90)", 
                 "[90 ~ 96)",
                 "[96 ~ 100]"), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  rev %>% 
  t %>% 
  `row.names<-`("Counts") %>%
# row.names(scores_tbl) <- "Counts"
# scores_tbl %>%
  cbind("계" = rowSums(.)) %>%
  t
Prop_tbl <- total$Total %>% 
  cut(breaks = c(0, 20, 40, 60, 90, 96, 100),
      labels = c("[0 ~ 20)", 
                 "[20 ~ 40)",
                 "[40 ~ 60)",
                 "[60 ~ 90)",
                 "[90 ~ 96)",
                 "[96 ~ 100]"), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  table %>%
  prop.table %>%
  `*`(100) %>%
  round(digits = 2) %>%
  rev %>% 
  t %>% 
  `row.names<-`("Percentages") %>%
# row.names(scores_tbl) <- "Counts"
# scores_tbl %>%
  cbind("계" = rowSums(.)) %>%
  t 
Grades <- c("A+", "B+", "C+", "C0", "D+", "D0")
# cbind(Counts_tbl, Prop_tbl, Grades) %>%
Cumulative_tbl <- cumsum(Prop_tbl)[-length(cumsum(Prop_tbl))]
cbind("Counts(명)" = Counts_tbl, 
      "Percentage(%)" = Prop_tbl, 
      "Cumulative Percentage(%)" = c(Cumulative_tbl, "")) %>%
  pander()
```

## 성적 등급 

```{r, message = FALSE, echo = FALSE}
# str(total)
total$Grades <- total$Total %>% 
  cut(breaks = c(0, 20, 40, 60, 90, 96, 100), 
      include.lowest = TRUE, 
      right = FALSE) %>%
  factor(levels = c("[96,100]", 
                    "[90,96)", 
                    "[60,90)",
                    "[40,60)",
                    "[20,40)", 
                    "[0,20)"),
         labels = c("A+", "B+", "C+", "C0", "D+", "D0"))
counts <- total$Grades %>%
  table %>% 
  c("계" = sum(.))
perc <- total$Grades %>%
  table %>% 
  prop.table %>%
  c("계" = sum(.)) %>%
  `*`(100) %>%
  round(digits = 2) 
#> 대체 수강자 중 A+ => A0
counts2 <- total$Grades %>%
  table %>% 
  c("계" = sum(.))
perc2 <- total$Grades %>%
  table %>%
  prop.table %>%
  c("계" = sum(.)) %>%
  `*`(100) %>%
  round(digits = 2) 
# rbind("Counts" = counts2, 
#       "Percentage" = perc2, 
#       "Cumulative" = cumsum(perc2)) %>%
#   cbind("Sum" = rowSums(.)) %>%
#  format(digits = 1, nsmall = 1) %>%
rbind("Counts" = format(counts2, digits = 1, nsmall = 0), 
      "Percentage(%)" = format(perc2, digits = 1, nsmall = 1), 
      "Cumulative(%)" = format(cumsum(perc2), digits = 1, nsmall = 1)) %>%
# cbind("Sum" = rowSums(.)) %>%
#   format(digits = 1, nsmall = 1) %>%
  `[<-`(3, 7, "") %>%
  kable(align = "r")
```
\newpage

## 성적 산출 내역

```{r, message = FALSE, echo = FALSE}
# str(total)
options(digits = 5)
total %>% 
  `[`(order(total$ID), ) %>%
  kable(align = c(rep("c", 2), rep("r", 6), "c"), row.names = FALSE) 
  
```

<!--
## 재수강을 고려한 특별 강등 요청

```{r, message = FALSE, echo = FALSE}
total[total$Name == "김수빈", ] %>%
  kable(align = c(rep("c", 2), rep("r", 6), "c"))
```

## Quiz 19점 이상

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Quiz >= 19, ], digits = 2, nsmall = 1),
      align = c(rep("r", 8), "c"))
nrow(total[total$Quiz >= 19, ])
```

## 60점 미만

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Total < 60, ], digits = 2, nsmall = 1),
      align = c(rep("r", 8), "c"))
nrow(total[total$Total < 60, ])
```
-->

<!--
## 50점 미만

```{r, eval = TRUE, echo = FALSE}
total[total$Total < 50, "Name"]
nrow(total[total$Total < 40, ])
```

##  A 학점자

```{r, eval = TRUE, echo = FALSE}
kable(format(total[total$Grades %in% c("A+", "A0"), ], digits = 2, nsmall = 1), 
      align = c(rep("r", 8), "c"), digits = 3)
nrow(total[total$Grades %in% c("A+", "A0"), ])
```
-->


<P style = "page-break-before:always">
<!--

```{r, individual scores, eval = TRUE, echo = FALSE}
v_names_kr <- c("학번", "이름", "온라인출석", "복습퀴즈", "TED 퀴즈", "데이터실험퀴즈", "구글설문지 참여", "총점", "등급")
total_kr <- total 
names(total_kr) <- v_names_kr
my_grade <- function(id){
  kable(total_kr[total$ID %in% id, -1], row.names = FALSE)
}
my_grade <- function(id){
  kable(total_kr[total$ID %in% id, -1], 
        row.names = FALSE)
}
# my_grade(c("20246942"))
# my_grade(c("이상민"))
```

```{r, eval = TRUE, echo = FALSE, results = 'asis'}
total_kr$"등급" %<>% 
  as.character
my_grade_print <-
  function(id){
    paste0(
      paste(names(total_kr[total$ID %in%  id, -1]),
            total_kr[total$ID %in% id, -1], 
            sep = " : "),
      c("", "/20", "/30", "/20", "/20", "/10", "/100", ""),
      collapse = "\t")
  }
my_grade_print("20214151") %>%
  data.frame(Grade_Report = .) %>%
  kable
#> x at the top remove
sapply(c("20171054", "20256785"), 
       FUN = my_grade_print) %>%
data.frame(Grade_Report = ., stringsAsFactors = FALSE) %>%
kable(escape = TRUE, row.names = FALSE, col.names = NA)
```

<!--
## Non-PASS

```{r, echo = FALSE}
#> List under 50
sapply(total[total$Total < 50, "ID"], 
       FUN = my_grade_print) %>%
  data.frame(Grade_Report = ., stringsAsFactors = FALSE) %>%
  kable(escape = FALSE, row.names = FALSE)
```
-->

<!--
### Save Data

```{r Save Data, echo = FALSE}
write.csv(army_records[order(army_records$ID), ], file = "./data/army_records_2502.csv", 
          row.names = FALSE,
          fileEncoding = "UTF-8")
army_records
total2501 <- total
saveRDS(total2501, file = "total2502.RDS")
save.image(file = "final_Records2502.RData")
```
-->
               