---
title: "Food Habits Comparison 2401"
author: "coop711"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(readxl)
library(pander)
library(knitr)
library(magrittr)
library(dplyr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

<!--
### Data 
-->

```{r, data, echo = FALSE, results = 'hide'}
class_roll <- readRDS("./class_roll_240503.RDS")
class_roll_id <- data.frame(id = class_roll$id, stringsAsFactors = FALSE) 
class_roll <- class_roll[c("id", "name", "group")] 
food_b <- readRDS("./food_before2401.rds")
b_id <- food_b$id
food_b <- left_join(class_roll, food_b, by = c("id", "group"))
str(food_b)
duplicated(food_b$id)
food_b <- unique(food_b)
food_a <- readRDS("./food_after2401.rds")
a_id <- food_a$id
food_a <- left_join(class_roll, food_a, by = c("id", "group"))
#> before 는 수행하고 after 는 안한 사람
setdiff(b_id, a_id) %>%
  `%in%`(class_roll$id, .) %>%
  `[`(class_roll, ., c("id", "name"))
# class_roll[class_roll$id %in% setdiff(b_id, a_id), c("id", "name")]
#> after 는 수행하고 before 는 안한 사람  
setdiff(a_id, b_id) %>%
  `%in%`(class_roll$id, .) %>%
  `[`(class_roll, ., c("id", "name"))
# class_roll[class_roll$id %in% setdiff(a_id, b_id), c("id", "name")]
str(food_a)
duplicated(food_a$id) 
food_a <- unique(food_a)
str(food_a)
diff <- food_a$score - food_b$score
food <- 
  data.frame(food_b[c("id", "group")], 
             score_b = food_b$score, 
             score_a = food_a$score, 
             diff = diff, 
             grade_b = food_b$grade, 
             grade_a = food_a$grade)
```

## 동영상 시청 전후 비교

### Cross Tables

```{r, cross table, echo = FALSE}
grade_tbl_b <- table(food$grade_b, useNA = "ifany")
grade_tbl_a <- table(food$grade_a, useNA = "ifany")
grade_tbl <- rbind(grade_tbl_b, grade_tbl_a)
grade_tbl_am <- addmargins(grade_tbl, margin = 2)
rownames(grade_tbl_am) <- c("시청 전", "시청 후")
colnames(grade_tbl_am)[4:5] <- c("불참", "계")
pander(grade_tbl_am)
```

### Percentages

```{r, echo = FALSE}
grade_ptbl <- prop.table(grade_tbl_am[, 1:3], margin = 1) * 100
grade_ptbl_am <- round(cbind(grade_ptbl, rowSums(grade_ptbl)), digits = 1)
colnames(grade_ptbl_am)[4] <- "계"
pander(grade_ptbl_am)
```

### Summary Statistics for `diff`

```{r, summary, echo = FALSE}
pander(summary(food$diff))
```

### Standard Deviation of `diff`

```{r, SD, echo = FALSE}
sd(food$diff, na.rm = TRUE)
```

### t-test for `diff` (One Sample)

```{r, t test, echo = FALSE}
pander(t.test(diff, alternative = "greater"))
```

### Histogram for `diff`

```{r, stem and leaf, echo = FALSE, message = FALSE}
library(extrafont)
par(family = "KoPubWorldDotum")
hist(food$diff, 
     freq = FALSE,
     ylim = c(0, 0.035),
     breaks = seq(-30, 80, by = 10), 
     main = "동영상 시청 전후 점수차이의 히스토그램",
     cex.main = 1.3,
     xlab = "점수 차이",
     col = "white")
d_mean <- summary(food$diff)["Mean"]
d_sd <- sd(food$diff, na.rm = TRUE)
d_x <- seq(from = d_mean - 3 * d_sd, to = d_mean + 3 * d_sd, length.out = 1000)
lines(d_x, dnorm(d_x, mean = d_mean, sd = d_sd), type = "l", col = "red")
```

### Box plot for `diff`

```{r, Box plot, echo = FALSE, fig.width = 7, fig.height = 7}
boxplot(diff, xlab = "diff")
```

## Red and Black (랜덤화 효과)

### Summary by Red and Black

```{r, summary_RnB, echo = FALSE}
pander(tapply(food$diff, food$group, summary))
```

### Standard Deviation by Red and Black

```{r, SD_RnB, echo = FALSE}
pander(tapply(food$diff, food$group, sd, na.rm = TRUE), caption = "Standard Deviation")
```

### t-test (Welch's) Red vs Black (Two Sample)

```{r, t test_RnB, echo = FALSE}
pander(t.test(diff ~ group, data = food))
```

### Histogram by Red and Black

```{r, stem and leaf_RnB, echo = FALSE, fig.width = 7, fig.height = 10}
par(family = "KoPubWorldDotum")
par(mfrow = c(2, 1))
hist(food$diff[food$group == "Red"], 
     freq = FALSE,
     ylim = c(0, 0.035),
     breaks = seq(-30, 80, by = 10), 
     main = "Red 그룹 점수 차이의 히스토그램",
     cex.main = 1.3,
     xlab = "Red",
     col = "white")
R_mean <- summary(food$diff[food$group == "Red"])["Mean"]
R_sd <- sd(food$diff[food$group == "Red"], na.rm = TRUE)
R_x <- seq(from = R_mean - 3 * R_sd, to = R_mean + 3 * R_sd, length.out = 1000)
lines(R_x, dnorm(R_x, mean = R_mean, sd = R_sd), type = "l", col = "red")
hist(food$diff[food$group == "Black"], 
     freq = FALSE,
     ylim = c(0, 0.035),
     breaks = seq(-30, 80, by = 10), 
     main = "Black 그룹 점수 차이의 히스토그램",
     cex.main = 1.3,
     xlab = "Black",
     col = "white")
B_mean <- summary(food$diff[food$group == "Black"])["Mean"]
B_sd <- sd(food$diff[food$group == "Black"], na.rm = TRUE)
B_x <- seq(from = B_mean - 3 * B_sd, to = B_mean + 3 * B_sd, length.out = 1000)
lines(B_x, dnorm(B_x, mean = B_mean, sd = B_sd), type = "l", col = "red")
```

### Box plot by Red and Black

```{r, Box plot_RnB, echo = FALSE, fig.width = 7, fig.height = 7}
plot(diff ~ group, data = food)
```

### 개별 식생활습관 등급 변화

```{r, grades, echo = FALSE}
# pander(food[c("id", "name", "score", "grade")])
kable(food, 
      col.names = c("학번", "그룹", "시청전 점수", "시청후 점수", "점수차이", "시청전등급", "시청후등급"),
      align = "c")
```


<!--
### save
-->

```{r, echo = FALSE}
save.image("./food2401.RData")
```