---
title: "Google Quiz 200914 Submission Time"
# author: "coop711"
# date: "2020-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(readr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide", message = FALSE}
load("./red_and_black_210308_data.RData")
quiz0228 <- read_excel("../data/quiz210228.xlsx",
                     range = "A1:J475",
                     col_names = TRUE)
quiz0228 <- quiz0228[c(1:4, 8)]        
names(quiz0228) <- c("time", "dept", "id", "name", "group")
class(quiz0228$id) <- "character"
quiz0228 <- dplyr::left_join(class_roll[, c("id", "group")], quiz0228, by = c("id", "group"))
# quiz0228$group <- class_roll$group[match(quiz0228$id, class_roll$id)]
quiz0228$submit <- ifelse(is.na(quiz0228$time), "미제출", "제출")
quiz0228$hours_passed <- as.numeric(difftime(Sys.time(), quiz0228$time, units = 'days'))
## 학교 정보시스템이 GMT로 표기되어 있어서 9시간의 타임갭을 감안하여야 함.
quiz0228$days <- as.numeric(difftime("2021-03-16 09:00:00", quiz0228$time, units = 'days'))
quiz0228$hours <- as.numeric(difftime("2021-03-16 09:00:00", quiz0228$time, units = 'hours'))
quiz0228$bird <- factor(ifelse(quiz0228$days >= 7, "Early", "Late"), 
                      labels = c("마감일 일주일 전 제출", "마감일 일주일 이내 제출"))
str(quiz0228)
```


### 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
pander(table(quiz0228$group, quiz0228$submit))
pander(chisq.test(table(quiz0228$group, quiz0228$submit)))
```

## 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

### 시간 단위 기초통계량

```{r, echo = FALSE}
# quiz0228$hours
summary(quiz0228$hours)
stem(quiz0228$hours)
max(quiz0228$hours, na.rm = TRUE)
```

<P style = "page-break-before:always">

### 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "KoPubWorldDotum Medium")
pander(table(cut(quiz0228$days, breaks = c(0:14), include.lowest = TRUE)), caption = "일 단위")
pander(chisq.test(table(cut(quiz0228$days, breaks = c(0:14), include.lowest = TRUE))))
barplot(rev(table(cut(quiz0228$days, breaks = c(0:14), include.lowest = TRUE))), 
        space = 0,
        names.arg = rep(c("화", "수", "목", "금", "토", "일", "월"), 2))
title(main = "일 단위 퀴즈 제출 횟수")
```

<P style = "page-break-before:always">
<!--
### 시간 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(0:10, seq(24, 168, by = 24))
breaks2 <- c(0:10, seq(24, 144, by = 24), 145:158, 168)
breaks3 <- c(0:6, 24:30, 48:54, seq(72, 144, by = 24), 145:150, 168)
breaks4 <- c(0:10, seq(24, 96, by = 24), 109:111, 120, 144, 157, 158, 168)
breaks5 <- c(0:10, seq(24, 144, by = 24), 157, 158, 168)
breaks6 <- c(0:10, seq(24, 96, by = 24), 109:111, 120, 144, 168)
breaks7 <- c(0:10, seq(24, 96, by = 24), 109:111, 120, 144:158, 168)
breaks8 <- c(0:10, seq(24, 96, by = 24), 97:111, 120, 144, 168)
breaks9 <- c(0:10, seq(24, 96, by = 24), 97:111, 120:130, 144, 168)
breaks10 <- c(0:10, seq(24, 96, by = 24), 101:110, 120, 144:158, 168)
pander(table(cut(quiz0228$hours, 
                 breaks = breaks, 
                 include.lowest = TRUE)), caption = "시간 단위")
```

### 시간 당 제출 건수의 분포

```{r, echo = FALSE}
par(family = "KoPubWorldDotum Medium")
widths <- rev(diff(breaks))
widths2 <- c(10, rep(1, 14), rep(24, 5), 14, rep(1, 10))
widths3 <- c(18, rep(1, 6), rep(24, 3), 18, rep(1, 6),  18, rep(1, 6), 18, rep(1, 6))
widths4 <- c(10, 1, 13, 24, 9, rep(1, 2), 13, rep(24, 3), 14, rep(1, 10))
widths5 <- c(10, 1, 13, rep(24, 5), 14, rep(1, 10))
widths6 <- rev(diff(breaks6))
widths7 <- rev(diff(breaks7))
widths8 <- rev(diff(breaks8))
widths9 <- rev(diff(breaks9))
widths10 <- rev(diff(breaks10))
freqs <- table(cut(quiz0228$hours, breaks = breaks, include.lowest = TRUE))
freqs2 <- table(cut(quiz0228$hours, breaks = breaks2, include.lowest = TRUE))
freqs3 <- table(cut(quiz0228$hours, breaks = breaks3, include.lowest = TRUE))
freqs4 <- table(cut(quiz0228$hours, breaks = breaks4, include.lowest = TRUE))
freqs5 <- table(cut(quiz0228$hours, breaks = breaks5, include.lowest = TRUE))
freqs6 <- table(cut(quiz0228$hours, breaks = breaks6, include.lowest = TRUE))
freqs7 <- table(cut(quiz0228$hours, breaks = breaks7, include.lowest = TRUE))
freqs8 <- table(cut(quiz0228$hours, breaks = breaks8, include.lowest = TRUE))
freqs9 <- table(cut(quiz0228$hours, breaks = breaks9, include.lowest = TRUE))
freqs10 <- table(cut(quiz0228$hours, breaks = breaks10, include.lowest = TRUE))
heights <- freqs / diff(breaks)
heights2 <- freqs2 / diff(breaks2)
heights3 <- freqs3 / diff(breaks3)
heights4 <- freqs4 / diff(breaks4)
heights5 <- freqs5 / diff(breaks5)
heights6 <- freqs6 / diff(breaks6)
heights7 <- freqs7 / diff(breaks7)
heights8 <- freqs8 / diff(breaks8)
heights9 <- freqs9 / diff(breaks9)
heights10 <- freqs10 / diff(breaks10)
names_args <- c("월", "화", "수", "목", "금", "토", "일", rep("", 10))
names_args2 <- c("월", rep("", 14),"화", "수", "목", "금", "토", "일", rep("", 10))
names_args3 <- c("수", rep("", 6),"목", "금", "토", "일", rep("", 6), "월", rep("", 6), "화", rep("", 6))
names_args4 <- c("월", rep("", 2), "화", "수", rep("", 3), "목", "금", "토", "일", rep("", 10))
names_args5 <- c("월", rep("", 2), "화", "수", "목", "금", "토", "일", rep("", 10))
names_args6 <- c("월", "화", "수", rep("", 3), "목", "금", "토", "일", rep("", 10))
names_args7 <- c("월", rep("", 14),"화", "수", rep("", 3), "목", "금", "토", "일", rep("", 10))
names_args8 <- c("월", "화", "수", rep("", 15), "목", "금", "토", "일", rep("", 10))
names_args9 <- c("월", "화", rep("", 10), "수", rep("", 15), "목", "금", "토", "일", rep("", 10))
names_args10 <- c("월", rep("", 14),"화", "수", rep("", 10), "목", "금", "토", "일", rep("", 10))
# barplot(height = rev(heights), width = widths, 
#         space = 0,
#         names.arg = names_args)
barplot(height = rev(heights), width = widths, 
        space = 0,
        names.arg = names_args)
title(main = "시간당 퀴즈 제출 분포")
# arrows(x0 = 3, y0 = 4.0, x1 = 9, y1 = 0.5, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 3, y = 4.5, labels = "오전 10시", srt = 9, col = "red")
# arrows(x0 = 47, y0 = 3.6, x1 = 56, y1 = 0.8, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 45, y = 4, labels = "오전 10시", srt = 16, col = "red")
arrows(x0 = 148, y0 = 3.2, x1 = 156, y1 = 1, length = 0.15, code = 2, col = "red", lwd = 1.5)
text(x = 145, y = 3.5, labels = "오후 2시", srt = 9, col = "red")
```
-->

<P style = "page-break-before:always">

### 급히 제출한 사람과 일찍 낸 사람 비교

마감일 일주일 전에 제출한 사람과 그 이후에 제출한 사람들의 특성 비교

#### 랜덤화 효과

```{r, echo = FALSE}
pander(table(quiz0228$group, quiz0228$bird))
pander(chisq.test(table(quiz0228$group, quiz0228$bird)))
```

<!--
#### 기초통계 비교

```{r, echo = FALSE, eval = FALSE}
pander(tapply(quiz0228$score1, quiz0228$bird, summary))
```

#### Box Plot

```{r, echo = FALSE, eval = FALSE}
par(family = "KoPubWorldDotum Medium")
plot(score1 ~ bird, data = quiz0228, 
     main = "마감일 오후 2시 전부터 제출한 사람과 그 이후에 낸 사람", 
     xlab = "제출 시점", ylab = "퀴즈 점수")
```

#### t test

```{r, echo = FALSE, eval = FALSE}
pander(t.test(score1 ~ bird, data = quiz0228))
```

## Save

```{r, echo = FALSE}
saveRDS(quiz0228, file = "quiz0228.RDs")
```
-->