---
title: "Red and Black 250221"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data}
class_roll <- readRDS("./class_roll_250225.RDS")
str(class_roll)
```

## Randomization

```{r, randomization}
set.seed(7488628)
N <- nrow(class_roll) 
class_roll$group <- 
  sample(1:N) %%
  2 %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
```

### 학년

```{r, year, eval = FALSE}
tbl0 <- class_roll$year %>%
  table(class_roll$group, .) 
tbl0 %>%
  pander
X0min <- tbl0 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X0min
```

### 학번

```{r, id}
class_roll$id_2 <-
  class_roll$id %>%
  substr(1, 4) %>%
  ifelse(. <= 2018 | . >= 2025, "18 or 25", .)
tbl1 <- class_roll %$%
  table(.$group, .$id_2) %>%
  `colnames<-`(c("18이전과 25", 2019:2024)) 
tbl1 %>%
  pander
X1min <- tbl1 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X1min
```

### 학번 홀짝

```{r, odd or even}
tbl2 <- class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) 
tbl2 %>%
  pander
X2min <- tbl2 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X2min
```

### 학적 상태

```{r, status}
tbl3 <- class_roll$status %>%
  table(class_roll$group, .) 
tbl3 %>%
  pander
X3min <- tbl3 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X3min
```

### e-mail 서비스업체

```{r, e_mail}
tbl4 <- class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  `==`("naver.com") %>%
  ifelse("네이버", "기타서비스") %>%
  factor(levels = c("네이버", "기타서비스")) %>%
  table(class_roll$group, .) 
tbl4 %>%
  pander
X4min <- tbl4 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X4min
```

### 전화번호의 분포

```{r, cell_no}
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
tbl5 <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric) %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) 
tbl5 %>%
  pander
X5min <- tbl5 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X5min
```

### 성씨 분포

```{r, name}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
tbl6 <- f_name %>%
  `%in%`(c("김", "이", "박", "최", "정")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "최", "정", "기타")) %>%
  table(class_roll$group, .) 
tbl6 %>%
  pander
X6min <- tbl6 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X6min
```

## 단과대학

```{r, college}
tbl7 <- 
  class_roll %$%
  table(.$group, .$college) 
tbl7 %>%
  pander
X7min <- tbl7 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1) 
X7min
```

### Sum of Chi_Squares

```{r}
Xsum_min <- X1min + X2min + X3min + X4min + X5min + X6min + X7min
Xsum_min
```

<!--
```{r, save}
saveRDS(class_roll, file = "./class_roll_250225.RDS")
# save.image("./red_and_black_240824_data.RData")
```
-->