---
title: "Red and Black : Search for the Best"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

# 02. Red and Black, 백만번을 열 번 돌려봤더니 ...

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
library(dplyr)
panderOptions('table.split.table', Inf)
```

## 실험의 목적

랜덤화 출석부를 생성하는 과정에 대하여 학습합니다. 

Red, Black 간에 닮은 정도를 측정하기 위하여 통계학에서 자주 등장하는 카이제곱 통계량을 도입합니다.

카이제곱 통계량의 확률분포를 규정하는 자유도, 기대값, 표준편차에 대하여 간단히 학습합니다. 

카이제곱 분포에서는 기대값이 바로 자유도라는 점도 알아 둘 필요가 있습니다.

학번만 가지고 Red, Black 이 가장 닮은 구성을 찾아 봅니다.

반복횟수를 백번, 천번, 만번, 십만번으로 늘려가면서 카이제곱 통계량의 최소값, 산술평균, 표준편차가 어느 값으로 수렴하는지 관찰합니다.

카이제곱 통계값들의 분포를 히스토그램과 밀도추정함수가 이론적인 카이제곱 분포의 확률밀도함수로 수렴하는 것도 관찰합니다.

학번과 나머지 4개 변수(e-mail 서비스업체, 전화번호 끝 네 자리,  5대 성씨분포, 단과대학)를 추가하여 위의 관찰을 반복합니다.

관찰한  내용을 퀴즈로 확인합니다.



## 얼마나 닮았나?

최적의 구성을 어떻게 찾은 것인지 그 과정을 알려 드립니다.  

카이제곱 분포 등 통계용어는 "아 그런 게 있나 보다"하면 됩니다. 

무대 뒤에서 돌아가는 일을 다 알 필요는 없으니까요. 

랜덤화 과정은 여러분에게 1번에서 812번까지 번호를 주고 그 번호를 랜덤하게 섞은 후 2로 나눈 나머지가 0이면 Red, 1이면 Black 으로 보내는 것입니다.

랜덤하게 섞는 과정에 초기값을 1번에서 100번, 1,000번, ... 백만번 등 필요한 횟수만큼 바꿔가면서 섞는 것을 반복하여 그 중 가장 닮은 구성을 찾습니다.

문제는 닮았다는 것을 어떻게 측정해서 알기 쉬운 숫자로 표시하는가인 데, 그 기준으로 카이제곱 통계량을 사용합니다. 

둘이 같으면 카이제곱값은 0이 되고, 둘의 차이가 크면 클수록 카이제곱 값도 커지면서 그 확률분포가 잘 알려져 있기 때문에 선택한 것입니다.

우선 학번에 대하여 Red, Black 을 나눈 카이제곱통계량이 가장 작아지는 구성을 찾아 봅시다.



## 학번만 고려할 때

학번은 2018학번 이전, 2019, 2020, 2021, 2022, 2023, 2024의 7개 범주로 나눕니다. 

2018 이전을 합쳐서 보는 이유는 카이제곱 통계량을 계산할 때 5명 이하인 범주가 있을 경우 확률  계산이 힘들어지기 때문입니다.

반복횟수를 100에서 10만까지 늘려가면서 각 시행마다 계산하여 나오는 카이제곱 통계량 (Xsum) 들의 분포를 추적합니다.

우선 100번 반복한 경우인 Red and Black : ID only (100 Trials) 를 열어 서 숫자를 확인합니다.

Summary 에는 기초통계값들을 나열하였습니다. Min.은 최소값, Median 은 중위수, Mean 은 산술평균, Max. 는 최대값입니다.

표준편차(SD)는  바로 밑에 나와 있습니다. 

여기서 유의할 점은 학번을 7개 범주로 나누었기 때문에 카이제곱 통계량의 자유도는 7 - 1 = 6이 됩니다. 

모든 범주의 합은 전체 인원과 같아지기 때문에 자유도가 하나 빠지는 것입니다.

그런데 카이제곱 분포의 기대값,  평균은  바로 자유도와 같습니다.

100회 반복하면서 계산한 카이제곱 값들은 마치 자유도 6인 카이제곱분포로부터 100개의 표본을 랜덤하게 뽑은 것과 같습니다.

따라서 그들의 평균은 기대값인 자유도에 가까워집니다. 

100번, 1,000번, 10,000번, 100,000번 반복횟수가 늘어가면서 Mean 이 6과 가까워지는 것을 관찰할 수 있습니다.

카이제곱 분포의 표준편차는 자유도의 2배에 제곱근을 취한 것입니다. 

자유도가 6이면 3.46 정도되는 것입니다. 

반복횟수가 늘어나면서 SD 도 3.46과 가까워지는 것을 관찰할 수 있습니다.

100개의 카이제곱 값중 최소값을 만든 초기값이 그 밑에 나와 있습니다.

최소값은 반복횟수가 늘어날수록 점점 작아지는 것을 알 수 있습니다.

Plot 은 히스토그램과 밀도추정함수를 그려보았는데 이 역시 반복횟수가 늘어남에 따라 자유도가 6인 카이제곱분포의 확률밀도함수에 가까워지는 관찰할 수 있습니다.

맨 밑에 Red, Black 간에 얼마나 닮았는지 분할표를 제시하고 그 밑에 카이제곱 통계값과 자유도 6인 카이제곱 분포에서 관찰된 카이제곱 통계값보다 큰 값이 나올 확률을 계산하였습니다. 

이 카이제곱 통계값이 바로 위의 기초통계값 중 최소값, Min. 입니다.


100번, 1000번, 10000번, 100000번 반복한 결과의 요약을 보면서 특히 다음 사항에 유의하세요.

(1) 최소값이 좀더 작은 값들이 나온다. 즉, 보다 닮은 구성을 찾을 수 있다.

(2) Mean 이 6에 점점 가까워진다. 

(3) SD, 표준편차는 3.46에 가까워진다.

(4) 히스토그램과 밀도추정함수가 자유도 6인 카이제곱분포의 확률밀도함수에 가까워진다. 

100000번 이상 반복할 이유가 왜 없는 지는 학번을 기준으로 Red, Black 을 나누었을 때 더 이상 닮기 힘들 정도이기 때문입니다.

[Red and Black 240906 : ID only (100 Trials)](http://rpubs.com/kwlee58/1267809)

[Red and Black 240906 : ID only (1,000 Trials)](http://rpubs.com/kwlee58/1267810)

[Red and Black 240906 : ID only (10,000 Trials)](http://rpubs.com/kwlee58/1267811)

[Red and Black 240906 : ID only (100,000 Trials)](http://rpubs.com/kwlee58/1267812)

단과대학이든 휴대폰 번호든 하나만 놓고 가장 닮은 구성을 구하면 이와 비슷한 결과 나올 것으로 충분히 짐작이 갈 것입니다. 



## 학번, 단과대학, e-mail 서비스업체, 전화번호 뒷 네자리, 5대 성씨 모두 고려

이제 학번과 단과대학 뿐 아니라 e-mail 서비스업체, 전화번호 뒷 네자리, 많이 나오는 성씨를 추가해서 100번 부터 백만번 10회 반복까지 수행한 결과를 올리겠습니다.

자유도가 32가 되는 과정은  학번(7-1) + e-mail 서비스업체(3 - 1) + 전화번호 끝 네자리(10 - 1) + 5대 성씨(6 - 1) + 단과대학(11 - 1) 입니다.

32가 흥미로운 숫자인 것은 산술평균이 그대로 32로 가까워져 가는 것을 볼 수 있을 뿐 아니라 표준편차가 32의 두 배에 제곱근을 취하면 8이 나오기 때문에 SD는 8에 가까워져 갑니다.

이번에는 다음 사항을 관찰할 수 있습니다.

100번, 1,000번, 10,000번, 100,000번, 1,000,000번 반복한 결과의 요약을 보면서 특히 다음 사항에 유의하세요.

(1) 최소값이 좀더 작은 값들이 나온다. 즉, 보다 닮은 구성을 찾을 수 있다.

(2) Mean 이 32에 대체적으로 점점 가까워진다. 

(3) SD, 표준편차는 대체적으로 8에 가까워진다.

(4) 히스토그램과 밀도추정함수가 자유도 32인 카이제곱분포의 확률밀도함수에 가까워진다. 

백만번씩 10회 반복한 실험은 그 중 가장 닮은 구성을 제공한 5번째 시행 결과만 수록하였습니다.

백만번 반복한 결과들은 복사한 듯이 비슷하기 때문입니다.

[Red and Black 240906 : Five Variables (100 Trials)](http://rpubs.com/kwlee58/1267813) 

[Red and Black 240906 : Five Variables (1,000 Trials)](http://rpubs.com/kwlee58/1267814)

[Red and Black 240906 : Five Variables (10,000 Trials)](http://rpubs.com/kwlee58/1267815)

[Red and Black 240906 : Five Variables (100,000 Trials)]() 

Red and Black 240906 : Five Variables (Fifth 1 Million Trials) 
