---
title: "Red and Black 240308 : Those who left"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
class_roll0226 <- readRDS("./class_roll0226.RDS")
# load("./red_and_black_230226_data.RData")
# class_roll0226 <- class_roll
nrow(class_roll0226)
class_roll <- read_excel("./data/class_roll240308.xlsx",
                         range = "B1:I914",
                         col_names = TRUE,
                         col_types = "text")
nrow(class_roll)
names(class_roll) <- 
  c("college", "dept", "year", "id", "name", "status", "email", "cell_no")
class_roll$status <- 
  ifelse(is.na(class_roll$status), "휴학", class_roll$status)
str(class_roll)
class_roll$group <- 
  class_roll0226$group[match(class_roll$id, class_roll0226$id)]
str(class_roll)
class_roll$college[class_roll$college == "공과대학"] <- "정보과학대학"
```

### 2월 26일자 출석부에만 나오는 사람들의 분포

```{r, echo = FALSE}
id_out <- setdiff(class_roll0226$id, class_roll$id)
id_new <- setdiff(class_roll$id, class_roll0226$id)
N_new <- length(id_new)
id_stay <- setdiff(class_roll0226$id, id_out)
class_roll0226[class_roll0226$id %in% id_out, c("id", "group")] %>%
  pander
class_roll0226$group %>%
  `[`(class_roll0226$id %in% id_out) %>%
  table %>%
  pander
N_stay <- class_roll0226$group %>%
  `[`(class_roll0226$id %in% id_stay) %>%
  length
red_stay <- class_roll0226$group %>%
  `[`(class_roll0226$id %in% id_stay) %>%
  table %>%
  `[`(1) %>%
  unname
N <- nrow(class_roll)
red_new <- floor((N - 2 * red_stay) / 2)
```


### 3월 8일 출석부에도 나오는 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll[class_roll$id %in% id_stay, ])
```

### 수강신청 변경으로 나간 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll0226[class_roll0226$id %in% id_out, ])
```

### 수강 신청 변경으로 새로 들어온 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll[class_roll$id %in% id_new, ])
```

### 남아 있던 사람들 + 새로 들어온 사람들

```{r, echo = FALSE}
str(class_roll)
```

### 100만번씩 10회 반복한 결과를 

```{r, sub randomization, echo = FALSE, eval = FALSE}
source("./RnB_2024_v5.R")
M1 <- 1
M2 <- 100000
Xsum <- sapply(M1:M2, red_and_black)
names(Xsum) <- M1:M2
Xsum %>%
  summary %>%
  round(2) 
Xsum %>%
  sd %>%
  round(2)
Xsum %>%
  `<=`(3) %>%
  which %>%
  `[`(Xsum, .) %>%
  round(2)
Xmin <- names(Xsum[which(Xsum == min(Xsum))])
Xmin
```

## Randomization

```{r, randomization}
Xmin <- 2508488
set.seed(Xmin)
id_red <- sample(1:N_new, size = red_new)
class_roll[class_roll$id %in% id_new, "group"] <- 
  factor(ifelse(1:N_new %in% id_red, "Red", "Black"), levels = c("Red", "Black")) 
class_roll[order(class_roll$name), c("id", "group")]
```

### 학번

```{r, id, echo = FALSE}
class_roll$id_2 <-
  class_roll$id %>%
  ifelse(. <= 2018, "2018", .)
tbl1 <- class_roll %$%
  table(.$group, .$id_2 %>% substr(1, 4)) %>%
  `colnames<-`(c("2018 이전", 2019:2024)) 
tbl1 %>%
  pander
class_roll <- class_roll[, names(class_roll0226)]
tbl1 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```

### 학번 홀짝

```{r, odd or even, echo = FALSE}
tbl2 <- class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) 
tbl2 %>%
  pander
tbl2 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```

### 학적 상태

```{r, status, eval = FALSE}
tbl3 <- class_roll$status %>%
  table(class_roll$group, .) 
tbl3 %>%
  pander
X3min <- tbl3 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X3min
```

### e-mail 서비스업체

```{r, e_mail, echo = FALSE}
isp <- class_roll$email %>%
    strsplit("@", fixed = TRUE) %>%
    sapply("[", 2) %>%
    strsplit("[.]", fixed = FALSE) %>%
    sapply("[", 1)
tbl4 <- isp %>%
    `%in%`(c("naver", "gmail")) %>%
    ifelse(isp, "기타서비스") %>%
    factor(levels = c("naver", "gmail", "기타서비스"),
           labels = c("네이버", "구글", "기타서비스")) %>%
    table(class_roll$group, .)  
tbl4 %>%
  pander
tbl4 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```

### 전화번호의 분포

```{r, cell_no, echo = FALSE}
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
tbl5 <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric) %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) 
tbl5 %>%
  pander
tbl5 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```
    
### 성씨 분포

```{r, name, echo = FALSE}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
tbl6 <- f_name %>%
  `%in%`(c("김", "이", "박", "최", "정")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "최", "정", "기타")) %>%
  table(class_roll$group, .) 
tbl6 %>%
  pander
tbl6 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```

### 단과대학

```{r, college, echo = FALSE, eval = TRUE}
tbl7 <- 
  class_roll %$%
  table(.$group, .$college) 
tbl7 %>%
  pander
tbl7 %>%
  chisq.test(simulate.p.value = FALSE) %>%
  pander
```

### Sum of Chi_Squares

```{r, eval = FALSE}
Xsum_min <- X1min + X2min + X4min + X5min + X6min + X7min
Xsum_min
```

### 전체 출석부

```{r}
class_roll %$%
  order(.$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  pander(caption = "가나다순", row.names = FALSE)
```

<P style="page-break-before:always">

```{r, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red")
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black")
```

<P style="page-break-before:always">

```{r, eval = TRUE}
class_roll %>%
  `[`(.$id %>% order, c("id", "group")) %>%
  saveRDS(file = "./class_id_group240308.RDS")
save.image("./red_and_black_240308_data.RData")
```
-->