---
title: "Red and Black 210228"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data}
class_roll <- read_excel("../data/class_roll210228.xlsx", 
                        range = "B1:G487")
str(class_roll)
names(class_roll) <- c("dept", "id", "name", "status", "email", "cell_no")
class_roll$status <- ifelse(is.na(class_roll$status), "휴학", class_roll$status)
str(class_roll)
```

## Randomization

```{r, randomization}
set.seed(16384)
N <- nrow(class_roll) 
class_roll$group <- 
  sample(1:N) %%
  2 %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
```

### 학번

```{r, id}
class_roll$id_2 <-
  class_roll$id %>%
  ifelse(. <= 2015, "2015", .)
class_roll %$%
  table(.$group, .$id_2 %>% substr(1, 4)) %>%
  `colnames<-`(c("2015 이전", 2016:2021)) %>%
  pander
```

### 학번 홀짝

```{r, odd or even}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학적 상태

```{r, status}
class_roll$status %>%
  table(class_roll$group, .) %>%
  pander
```

### e-mail 서비스업체

```{r, e_mail}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  `==`("naver.com") %>%
  ifelse("네이버", "기타서비스") %>%
  factor(levels = c("네이버", "기타서비스")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 전화번호의 분포

```{r, cell_no}
par(family = "KoPubWorldDotum Bold")
cell_numbers <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric)
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
  kable
cell_numbers %>%
  hist(main = "전화번호 끝 네 자리의 분포")
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table %>%
  chisq.test
```

### 많이 나오는 성씨

```{r, frequent names}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
f_name  %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학과

```{r, departments}
class_roll %$%
  table(.$group, .$dept) %>%
  pander
```

### 전체 출석부

```{r, colleges}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  pander(row.names = FALSE)
```

<P style="page-break-before:always">

```{r, list, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red")
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black")
```

<!--
```{r, save}
save.image("./red_and_black_210228_data_opt.RData")
```
-->