---
title: "랜덤화 출석부(240824)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

<!--
### Data

```{r, data, echo = FALSE}
class_roll <- readRDS("./class_roll_240824.RDS")
```

### 전체 출석부
-->

```{r, echo = FALSE}
class_roll %$%
  order(.$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  pander(caption = "가나다순", row.names = FALSE)
```

<P style="page-break-before:always">

```{r, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red", row.names = FALSE)
```

<P style="page-break-before:always">

```{r, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black", row.names = FALSE)
```

<P style="page-break-before:always">

