---
title: "랜덤화 출석부 (250308)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pander)
library(knitr)
library(magrittr)
library(dplyr)
library(tidyr)
panderOptions('table.split.table', Inf)
```


<!--
### Data

```{r, data, echo = FALSE}
class_roll0225 <- readRDS("./class_roll_250225.RDS")
# class_roll <- readRDS("./class_roll_250308.RDS")
load("./red_and_black_250308_data.RData")
```
-->

## 수강변경 기간 중 들어온 사람들

```{r, echo = FALSE}
class_roll %>%
  subset(., subset = .$id %in% id_new) %>%
  arrange(name) %>%
  select(id, name, group) %>%
#  rename("학번" = id, "이름" = name, "그룹" = group) %>%
#  setNames(c("학번", "이름", "그룹")) %>%
  pander(caption = "가나다순", col.names = c("학번", "이름", "그룹"), row.names = FALSE)
```

## 그룹이 바뀐 사람들

```{r, echo = FALSE}
# 1. 각 데이터에 날짜 정보 추가
class_roll0225 <- class_roll0225 %>%
  mutate(date = "0225")

class_roll <- class_roll %>%
  mutate(date = "0308")

# 2. 두 데이터 결합 (id와 날짜를 기준으로)
combined_class_roll <- bind_rows(class_roll0225, class_roll) 

# 데이터를 wide format 으로 변환하여 각 id 의 두 날짜별 그룹을 한 행에 정렬
wide_class_roll <- combined_class_roll %>%
  select(id, name, date, group) %>%
  pivot_wider(names_from = date, values_from = group, names_prefix = "group_") %>%
  mutate(group_changed = group_0225 != group_0308)

# 날짜별로 그룹이 바뀐 사람들확인
wide_class_roll %>%
  select(id, name, group_0225, group_0308, group_changed) %>%
  filter(group_changed == TRUE) %>%
  select(id, name, group_0225, group_0308) %>%
  arrange(name) %>%
  pander(col.names = c("학번", "이름", "2월25일 그룹", "3월8일 그룹"))

# 교차표
cross_tab <- table(wide_class_roll$group_0225, wide_class_roll$group_0308)
dimnames(cross_tab) <- 
  list("2월25일" = rownames(cross_tab), "3월8일" = colnames(cross_tab))
cross_tab %>% 
  pander
```

## 그룹이 바뀌지 않은 사람들

```{r, echo = FALSE}
# 날짜별로 그룹이 바뀐 사람들확인
wide_class_roll %>%
  select(id, name, group_0225, group_0308, group_changed) %>%
  filter(group_changed == FALSE) %>%
  select(id, name, group_0225, group_0308) %>%
  arrange(name) %>%
  pander(col.names = c("학번", "이름", "2월25일 그룹", "3월8일 그룹"))
```

## 전체 랜덤화 출석부 (3월8일 기준)

```{r, echo = FALSE}
class_roll %>%
  arrange(name) %>%
  select(id, name, group) %>%
  pander(caption = "가나다순", colnames = c("학번", "이름", "그룹"), row.names = FALSE)
```

<P style="page-break-before:always">

## Red

```{r, echo = FALSE}
class_roll %>%
  arrange(group, name) %>%
  select(group, id, name) %>%
  filter(group == "Red") %>%
  select(id, name) %>%
  pander(caption = "Red", colnames = c("학번", "이름"), row.names = FALSE)
```

<P style="page-break-before:always">

## Black

```{r, echo = FALSE}
class_roll %>%
  arrange(group, name) %>%
  select(group, id, name) %>%
  filter(group == "Black") %>%
  select(id, name) %>%
  pander(caption = "Black", colnames = c("학번", "이름"), row.names = FALSE)
saveRDS(class_roll, file = "./class_roll_250308.RDS")
```

<P style="page-break-before:always">

